# -*- coding: utf-8 -*-
"""1.d.1 Clean Unrelated and Low quality task samples

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ksAcYaM-Hhppnbr1cOs_F-AC7eSe_c8
"""

import json

unrelated_det = list(set([1, 22, 44, 48, 50, 55, 80, 84, 92, 100, 102, 124, 135, 156, 157, 180, 181, 181, 197, 249, 254, 274, 275, 353, 405, 411, 417, 418, 421, 426, 449, 521, 548, 554, 588, 611, 614, 615, 616, 618, 619, 626, 628, 631, 632, 633, 635, 637, 641, 643, 647, 654, 662, 667, 670, 671, 672, 673, 675, 681, 682, 687, 688, 689, 690, 692, 696, 699, 702, 704, 710, 712, 713, 718, 719, 722, 728, 732, 734, 735, 737, 740, 741, 745, 746, 751, 752, 759, 760, 761, 762, 766, 769, 770, 772, 775, 777, 785, 786, 787, 789, 795, 797, 798, 799, 802, 803, 805, 809, 811, 813, 815, 819, 823, 824, 826, 827, 828, 829, 831, 832, 835, 839, 840, 841, 845, 846, 848, 850, 854, 856, 858, 861, 863, 865, 866, 870, 873, 875, 876, 880, 882, 883, 884, 886, 887, 888, 894, 896, 897, 898, 901, 902, 904, 905, 906, 907, 909, 911, 914, 918, 920, 921, 923, 924, 926, 928, 932, 933, 936, 938, 941, 943, 945, 948, 951, 952, 954, 954, 955, 962, 963, 966, 971, 973, 979, 982, 986, 993, 1002, 1005, 1006, 1007, 1011, 1028, 1068, 1097, 1101, 1115, 1136, 1196, 1209, 1223, 1224, 1241, 1245, 1260, 1284, 1301, 1336, 1362, 1374, 1376, 1383, 1398, 1428, 1434, 1435, 1495, 1525, 1533, 1535, 1537, 1539, 1541, 1563, 1579, 1632, 1638, 1670, 1675, 1680, 1686, 1695, 1702, 1704, 1726, 1752, 1757, 1769, 1801, 1817, 1821, 1833, 1856, 1889, 1920, 1930, 1934, 1937, 1954, 1956, 1974, 1975, 2000, 2043, 2107, 2130, 2134, 2135, 2144, 2159, 2241, 2247, 2268, 2287, 2288, 2295, 2318, 2333, 2339, 2355, 2357, 2371, 2389, 2393, 2396, 2440, 2450, 2499, 2506, 2516, 2576, 2583, 2591, 2620, 2622]))

with open("complete_answers.json", "r") as f:
  data = json.load(f)

problem_qs = []

for task_sample in data:
  question = task_sample["question"]
  answer = task_sample["complete_answer"]

  if "LLM failed" in answer:
    print(question)
    problem_qs.append(question)

with open("clean_follow_up_questions.json", "r") as f:
  data = json.load(f)

problem_ids = []

ungenerated_id = []

for task_sample in data:
  id = task_sample["id"]
  question = task_sample["question"]
  answer = task_sample["answer"]
  follow_up_questions = task_sample["follow-ups"]

  for qs in problem_qs:
    if qs in question:
      # print(id)
      problem_ids.append(id)

  for fq in follow_up_questions:
    if "LLM failed" in fq:
      # print(id)
      ungenerated_id.append(id)
# print(len(problem_ids))
# print(len(ungenerated_id))
# print(problem_ids)
# print(ungenerated_id)

problem_ids.extend(ungenerated_id)
problem_ids = list(set(problem_ids))
print(len(problem_ids))
print(problem_ids)

problem_ids = [900, 134, 1288, 527, 1304, 283, 543, 1696, 562, 1846, 1078, 952, 2617, 2618, 2492, 2243, 1095, 2643, 859, 2141, 607, 1121, 866, 1892]

with open("clean_follow_up_questions.json", "r") as f:
  data = json.load(f)

print(len(data))
update_data = []

for task_sample in data:
  id = task_sample["id"]
  if id not in problem_ids:
    update_data.append(task_sample)

print(len(update_data))

json_data = json.dumps(update_data, indent=2)

with open("update_follow_up_questions.json", "w") as f:
    f.write(json_data)

with open("update_follow_up_questions.json", "r") as f:
  data = json.load(f)

unrelated = []

for task_sample in data:
  id = task_sample["id"]
  question = task_sample["question"]
  answer = task_sample["answer"]
  follow_up_question = task_sample["follow-ups"][1]
  # if id in unrelated_det:
  #   print(question)
  #   print(answer)
  #   print(follow_up_question)
  #   judgement = input("Press x for actually unrelated task samples: ")
  #   if judgement == "x":
  #     unrelated.append(id)
  #   else:
  #     continue

# print(unrelated)

unrelated = [156, 274, 405, 611, 614, 615, 616, 618, 619, 628, 631, 632, 633, 635, 637, 641, 643, 647, 654, 662, 667, 670, 671, 672, 673, 675, 682, 687, 688, 690, 692, 696, 699, 702, 704, 710, 712, 713, 718, 719, 728, 732, 734, 735, 737, 740, 741, 745, 746, 751, 752, 759, 760, 761, 762, 766, 769, 770, 772, 775, 777, 785, 786, 787, 789, 797, 798, 802, 803, 805, 809, 811, 813, 815, 819, 823, 824, 828, 829, 831, 832, 835, 839, 840, 841, 845, 846, 848, 850, 854, 856, 858, 861, 865, 870, 873, 875, 876, 880, 882, 883, 884, 886, 887, 888, 894, 896, 897, 898, 901, 902, 904, 905, 906, 907, 909, 911, 914, 918, 921, 923, 924, 926, 928, 932, 933, 936, 938, 941, 943, 945, 948, 951, 954, 955, 962, 963, 966, 971, 973, 979, 982, 993, 1002, 1005, 1006, 1007, 1028, 1097, 1196, 1374, 1376, 1383, 1398, 1435, 1533, 1539, 1541, 1579, 1632, 1686, 1695, 1726, 1833, 1937, 2144, 2339]

print(len(unrelated))

# with open("train_org.json", "r") as f:
#   org_data = json.load(f)

# with open("update_follow_up_questions.json", "r") as f:
#   new_data = json.load(f)

# problem_q_org = []

# for task_sample in new_data:
#   id = task_sample["id"]
#   if id in unrelated:
#     problem_q_org.append(task_sample["question"])

# for task_sample in org_data:
#   question = task_sample["question"]
#   answer = task_sample["answer"]
#   relation = task_sample["relation"]

#   if question in problem_q_org:
#     print(question)
#     print(answer)
#     print(relation)

with open("update_follow_up_questions.json", "r") as f:
  data = json.load(f)

print(len(data))
update_data = []

for task_sample in data:
  id = task_sample["id"]
  if id not in unrelated:
    update_data.append(task_sample)

print(len(update_data))

json_data = json.dumps(update_data, indent=2)

with open("update_follow_up_questions.json", "w") as f:
    f.write(json_data)

